name: Lint

on:
  pull_request:

jobs:
  biome:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Biome CLI
        uses: biomejs/setup-biome@v2

      - name: Run Biome
        run: biome ci .

  tsc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Run TypeScript
        run: npm run typecheck
